// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkgSZUcbs5g9oQ2TV0-8GHM3QkzvJ4StU',
    appId: '1:200592717469:web:fdad334eafbf5ab6e4c674',
    messagingSenderId: '200592717469',
    projectId: 'eventflow-4cbc6',
    authDomain: 'eventflow-4cbc6.firebaseapp.com',
    storageBucket: 'eventflow-4cbc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1o0JcrdltEDOAl9720hozwScHx4Kf5kI',
    appId: '1:200592717469:android:5ae1df74a14363b7e4c674',
    messagingSenderId: '200592717469',
    projectId: 'eventflow-4cbc6',
    storageBucket: 'eventflow-4cbc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnFXw-Lzd6DQopsGVWoVeK-TXKjM5tEtQ',
    appId: '1:200592717469:ios:9289d41e90f56b0ae4c674',
    messagingSenderId: '200592717469',
    projectId: 'eventflow-4cbc6',
    storageBucket: 'eventflow-4cbc6.appspot.com',
    iosBundleId: 'com.example.eventFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnFXw-Lzd6DQopsGVWoVeK-TXKjM5tEtQ',
    appId: '1:200592717469:ios:ddca76fb7ba74f51e4c674',
    messagingSenderId: '200592717469',
    projectId: 'eventflow-4cbc6',
    storageBucket: 'eventflow-4cbc6.appspot.com',
    iosBundleId: 'com.example.eventFlow.RunnerTests',
  );
}
